# Generated by Django 5.1.1 on 2024-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('year', models.IntegerField(max_length=4)),
                ('category', models.CharField(max_length=24)),
                ('rating', models.CharField(max_length=8)),
                ('isBookmarked', models.BooleanField()),
                ('isTrending', models.BooleanField()),
            ],
        ),
    ]
